### ISSUE TITLE
Error: 'KernelPCA' object has no attribute 'lambdas_'

### ISSUE THREAD

**Issue by weiycfs** [I-Hope-Peace/KPCAMNet#4]
train_KPCAMNet.py:
 115 eig_value = PCANet_model.filters[-1].lambdas_

'KernelPCA' object has no attribute 'lambdas_'

**Comment by ChenHongruixuan** [comment]
Hi, many thanks for your question and your interests to our work! The error seems to be caused by the fact that we are using different versions of the scikit-learn library. In the version I was using, the eigenvalues variable was named lambdas_. And in the more recent version, the variable is named eigenvalues_.
